### ISSUE TITLE
There are problems when trying to commit suicide by fall damage.

### ISSUE THREAD

**Issue by BenF29** [TheAssassin13/tankProject#2]
If it's the last game the scoreboard bugs out.
If it's not the last game, the player doesn't reappears with full health. (My guess is that the animation timer for fall damage continues damaging even when in the interlude menu)

To replicate, you can shoot the ground with 100 power, the shot won't damage the tank, but the fall will.

![imagen](https://github.com/TheAssassin13/tankProject/assets/108445832/abffb88b-7a76-4ad8-aae6-370a797850b1)

**Comment by BenF29** [comment]
I was checking the tankFallAnimationTimer method, but it should stop when the tank is destroyed. I don't understand how it continues damaging the tank.

A possible solution could be doing this in the intialize of the GameController instead of the InterludeController:
`for (Player player : Data.getInstance().alivePlayers) {
            player.tank.restoreHealth();
            Shop.LoadCredits(player,Constants.INITIAL_CREDITS);
        }`

I want to know your opinion on this "solution".

**Comment by vicetr3s** [comment]
I have not been able to replicate the scoreboard bug, but I have been able to replicate the tank health bug. 
I think you're right, it's because it switches to the Interlude class before the end of the tank's fall. So in the interlude class it regenerates the tank's health but in the remaining fall it takes away some health.
Your solution may work, but we will have to move all related methods. Maybe we can add a delay before switching to the Interlude class. Although I don't think it's an elegant solution, but it will help to give some time for the user to understand what's going on in the game.

**Comment by BenF29** [comment]
Thanks, I agree on the delay before going to the interlude menu. I was thinking about it before, sometimes the user doesn't know if a tank is destroyed at the last second or so. It would be great if you could implement this delay, I don't know exactly how to do it and you've worked on delays before.

About the scoreboard bug, it seems I fixed it by accident, which is hilarious.

**Comment by vicetr3s** [comment]
Great!, and yeah, I can implement it, assign the issue to me.

**Comment by vicetr3s** [comment]
The delay fixed the bug, I'm gonna close the issue.
